version: "3.8"

services:
  storage:
    image: minio/minio:latest
    entrypoint: sh
    command: -c "mkdir -p /data/test-bucket && minio server /data --console-address \":9001\""
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=test_access_key
      - MINIO_ROOT_PASSWORD=test_secret_key
      - MINIO_REGION_NAME=ap-northeast-2
